# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RxSwift-Table-Collection' do

  use_frameworks!

pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'
pod 'Kingfisher'

end
